name: Update NPM Dependencies
description: 'Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files'
inputs:
    name:
      description: 'The name who you want to say hello to.'
      required: true

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you
    
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}